<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- 用於處理 Excel 檔案的套件，您可以根據需要選擇其中一個 -->
    <!-- 
    <PackageReference Include="EPPlus" Version="7.0.0" />
    -->
    <!-- 
    <PackageReference Include="ClosedXML" Version="0.102.1" />
    -->
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
  </ItemGroup>

</Project>